import crypto from "crypto";
import bcrypt from "bcryptjs";
import mongoose from "mongoose";
import Account from "../Account/model/Account";
import Employee from "../Employee/model/Employee";
import Student from "../Student/model/Student";
import studentPortalService from "../Student/studentPortalService";
import { sendOtpEmail } from "../../utils/resendMailer";
import Parent from "./model/Parent";
import PortalChatMessage from "../Employee/model/PortalChatMessage";

const hash = (value: string) => crypto.createHash("sha256").update(String(value || "")).digest("hex");
const esc = (value: string) => String(value || "").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

class ParentService {
  private async account(accountCode: string) { const value: any = await Account.findOne({ account_code: { $regex: new RegExp(`^${esc(accountCode.trim())}$`, "i") }, status: { $ne: 0 } }).lean(); if (!value) throw new Error("Account not found"); return value; }
  private publicParent(parent: any) { return { _id: parent._id, name: parent.name, email: parent.email, phone: parent.phone, username: parent.username, client: parent.client, children: parent.children, status: parent.status }; }
  private async validateChildren(client: string, ids: string[]) { if (!ids?.length || ids.some((id) => !mongoose.Types.ObjectId.isValid(id))) throw new Error("Select at least one valid child"); const children = await Student.find({ _id: { $in: ids }, client, deleted: { $ne: true }, status: { $ne: 0 } }).select("_id name student_key class_batch").lean(); if (children.length !== new Set(ids.map(String)).size) throw new Error("One or more children are invalid"); return children; }

  async list(client: string) { return Parent.find({ client, deleted: { $ne: true } }).select("-password -otp_hash -access_token_hash").populate("children", "name student_key class_batch").sort({ name: 1 }).lean(); }
  async create(data: any) { await this.validateChildren(data.client, data.children); if (!data.password || String(data.password).length < 8) throw new Error("Password must be at least 8 characters"); return this.publicParent(await Parent.create({ ...data, email: String(data.email).trim().toLowerCase(), username: String(data.username).trim().toLowerCase(), password: await bcrypt.hash(String(data.password), 10) })); }
  async update(id: string, data: any) { const parent: any = await Parent.findOne({ _id: id, deleted: { $ne: true } }).select("+password"); if (!parent) throw new Error("Parent not found"); if (data.children) await this.validateChildren(parent.client, data.children); Object.assign(parent, data); if (data.password) { if (String(data.password).length < 8) throw new Error("Password must be at least 8 characters"); parent.password = await bcrypt.hash(String(data.password), 10); } await parent.save(); return this.publicParent(parent); }

  async requestOtp(accountCode: string, email: string) { const account = await this.account(accountCode); const parent: any = await Parent.findOne({ client: account.account_key, email: email.trim().toLowerCase(), deleted: { $ne: true }, status: 1 }).select("+otp_hash +otp_expires_at"); if (!parent) throw new Error("Parent account not found"); const otp = String(crypto.randomInt(100000, 1000000)); parent.otp_hash = hash(otp); parent.otp_expires_at = new Date(Date.now() + 600000); await parent.save(); await sendOtpEmail({ to: parent.email, name: parent.name, otp, subject: "Your Parent Portal OTP", purpose: "access your children dashboard", expiresInMinutes: 10 }); return { email: parent.email.replace(/(^..).*(@.*$)/, "$1***$2") }; }
  async verifyOtp(accountCode: string, email: string, otp: string) { const account = await this.account(accountCode); const parent: any = await Parent.findOne({ client: account.account_key, email: email.trim().toLowerCase(), otp_hash: hash(otp), otp_expires_at: { $gt: new Date() }, deleted: { $ne: true }, status: 1 }).select("+otp_hash +otp_expires_at +access_token_hash +access_token_expires_at"); if (!parent) throw new Error("OTP is invalid or expired"); return this.issue(parent); }
  async login(accountCode: string, username: string, password: string) { const account = await this.account(accountCode); const parent: any = await Parent.findOne({ client: account.account_key, username: username.trim().toLowerCase(), deleted: { $ne: true }, status: 1 }).select("+password +access_token_hash +access_token_expires_at"); if (!parent?.password || !(await bcrypt.compare(password, parent.password))) throw new Error("Invalid username or password"); return this.issue(parent); }
  private async issue(parent: any) { const token = crypto.randomBytes(32).toString("hex"); parent.otp_hash = ""; parent.otp_expires_at = null; parent.access_token_hash = hash(token); parent.access_token_expires_at = new Date(Date.now() + 12 * 3600000); await parent.save(); return { access_token: token, expires_in_hours: 12, parent: this.publicParent(parent) }; }
  async authorized(accountCode: string, parentId: string, token: string) { const account = await this.account(accountCode); const parent: any = await Parent.findOne({ _id: parentId, client: account.account_key, access_token_hash: hash(token), access_token_expires_at: { $gt: new Date() }, deleted: { $ne: true }, status: 1 }).select("+access_token_hash +access_token_expires_at"); if (!parent) throw new Error("Parent session is invalid or expired"); return parent; }
  async getData(accountCode: string, parentId: string, token: string, childId?: string) { const parent = await this.authorized(accountCode, parentId, token); await parent.populate("children", "name student_key class_batch"); const children: any[] = parent.children || []; const selected = children.find((child: any) => String(child._id) === String(childId)) || children[0]; return { parent: this.publicParent(parent), children, selected_child_id: selected?._id || null, childData: selected ? await studentPortalService.getDataForLinkedChild(String(selected._id), parent.client) : null }; }

  private async linkedChild(parent: any, childId: string) { if (!(parent.children || []).some((id: any) => String(id) === String(childId))) throw new Error("Child is not linked to this parent"); const child: any = await Student.findOne({ _id: childId, client: parent.client, deleted: { $ne: true }, status: { $ne: 0 } }).lean(); if (!child) throw new Error("Linked child not found"); return child; }
  private conversationKey(parentId: any, teacherId: any, childId: any) { return [`parent:${parentId}`, `staff:${teacherId}`, `child:${childId}`].join("|"); }
  async chatContacts(accountCode: string, parentId: string, token: string, childId: string) { const parent = await this.authorized(accountCode, parentId, token); const child = await this.linkedChild(parent, childId); const classes = [child.class_batch, ...(child.courses || []).filter((c:any)=>!c.deleted).map((c:any)=>c.course_name)].filter(Boolean); const teachers:any[] = await Employee.find({ client: parent.client, staff_type: "teaching", classes: { $in: classes }, deleted: { $ne: true }, status: { $ne: 0 } }).select("name employee_id designation subjects").sort({name:1}).lean(); return Promise.all(teachers.map(async teacher=>{const key=this.conversationKey(parent._id,teacher._id,child._id);const [unread,count]=await Promise.all([PortalChatMessage.countDocuments({conversation_key:key,recipient_kind:"parent",recipient_id:parent._id,read_at:null}),PortalChatMessage.countDocuments({conversation_key:key})]);return{id:teacher._id,kind:"staff",name:teacher.name,role_label:"Teacher",subtitle:`${teacher.designation||"Teacher"} · ${child.name}`,unread,has_chat:count>0};})); }
  async chatMessages(accountCode:string,parentId:string,token:string,childId:string,teacherId:string){const parent=await this.authorized(accountCode,parentId,token);const child=await this.linkedChild(parent,childId);const contacts=await this.chatContacts(accountCode,parentId,token,childId);if(!contacts.some((c:any)=>String(c.id)===String(teacherId)))throw new Error("Teacher is not assigned to this child");const key=this.conversationKey(parent._id,teacherId,child._id);await PortalChatMessage.updateMany({conversation_key:key,recipient_kind:"parent",recipient_id:parent._id,read_at:null},{$set:{read_at:new Date()}});const rows:any[]=await PortalChatMessage.find({conversation_key:key}).select("sender_kind message read_at createdAt").sort({createdAt:1}).lean();return rows.map(row=>({...row,sender_role:row.sender_kind==="parent"?"parent":"teacher"}));}
  async sendChat(accountCode:string,parentId:string,token:string,childId:string,teacherId:string,message:string){const parent=await this.authorized(accountCode,parentId,token);const child=await this.linkedChild(parent,childId);const contacts=await this.chatContacts(accountCode,parentId,token,childId);if(!contacts.some((c:any)=>String(c.id)===String(teacherId)))throw new Error("Teacher is not assigned to this child");const text=message.trim();if(!text)throw new Error("Message is required");return PortalChatMessage.create({client:parent.client,conversation_key:this.conversationKey(parent._id,teacherId,child._id),sender_kind:"parent",sender_id:parent._id,recipient_kind:"staff",recipient_id:teacherId,message:text});}
}
export default new ParentService();
